import { Quest } from '../constants/types';
// @ts-ignore — file added by user; alias resolves via tsconfig @assets → assets/
import sampleImage from '@assets/sample.png';

export const QUESTS: Quest[] = [
  {
    id: 'q1',
    kind: 'competitive',
    theme: 'FANTASY',
    title: 'The Embergate Crown',
    hook: 'A stolen crown. A burning forest. You have one chapter to choose a side.',
    heroHue: 18,
    heroHue2: 340,
    players: 2418,
    timeLeft: '14h 22m',
    size: 12,
    chapter: null,
    reward: 450,
    joined: false,
    lives: null,
    evalMode: 'AI',
    tag: 'HOT',
    image: sampleImage,
  },
  {
    id: 'q2',
    kind: 'competitive',
    theme: 'SURVIVAL',
    title: 'Last Light on Pier 9',
    hook: 'The storm took the mainland. Find shelter before the tide returns.',
    heroHue: 210,
    heroHue2: 260,
    players: 1209,
    timeLeft: '06h 41m',
    size: 16,
    chapter: 4,
    progress: 0.31,
    reward: 620,
    joined: true,
    lives: 2,
    maxLives: 3,
    evalMode: 'SOCIAL',
    tag: 'IN-PROGRESS',
    image: sampleImage,
  },
  {
    id: 'q3',
    kind: 'custom',
    theme: 'CRIME',
    title: 'Rooftops of Old Prague',
    hook: 'Your crew. Your rules. A heist that only works if the photos check out.',
    heroHue: 280,
    heroHue2: 330,
    players: 6,
    timeLeft: null,
    size: 8,
    chapter: null,
    reward: null,
    joined: false,
    lives: null,
    evalMode: 'SOCIAL',
    tag: 'CUSTOM',
    host: 'You + 5 friends',
    image: sampleImage,
  },
  {
    id: 'q4',
    kind: 'competitive',
    theme: 'SCI-FI',
    title: 'Signals from Ceres-4',
    hook: 'Something in the broadcast is not code. Decode it before it decodes you.',
    heroHue: 185,
    heroHue2: 155,
    players: 3102,
    timeLeft: '22h 05m',
    size: 12,
    chapter: null,
    reward: 500,
    joined: false,
    lives: null,
    evalMode: 'AI',
    tag: 'NEW',
    image: sampleImage,
  },
  {
    id: 'q5',
    kind: 'custom',
    theme: 'EDU',
    title: 'Biome Detectives',
    hook: 'A weekend nature hunt disguised as a rescue mission. Photos from real walks.',
    heroHue: 130,
    heroHue2: 90,
    players: 12,
    timeLeft: null,
    size: 12,
    chapter: 2,
    progress: 0.16,
    reward: null,
    joined: true,
    lives: 3,
    maxLives: 3,
    evalMode: 'AI',
    tag: 'IN-PROGRESS',
    host: 'Family group',
    image: sampleImage,
  },
  {
    id: 'q6',
    kind: 'competitive',
    theme: 'HORROR',
    title: 'The Hour of the Willow',
    hook: 'A town where midnight comes twice. Survive to witness the second.',
    heroHue: 300,
    heroHue2: 250,
    players: 845,
    timeLeft: '02h 11m',
    size: 16,
    chapter: null,
    reward: 780,
    joined: false,
    lives: null,
    evalMode: 'AI',
    tag: 'ENDING SOON',
    image: sampleImage,
  },
];

export const fmt = (n: number): string =>
  n >= 1000
    ? (n / 1000).toFixed(n >= 10000 ? 0 : 1).replace('.0', '') + 'k'
    : String(n);
